import {
  goToSettleEditStep,
  goToConfirmStep,
  isMemberEntry,
  isInputablePassword,
  isInputablePrivacyAgree,
  paymentMethods,
  isSelectedCreditCard,
  paymentTimeChoices,
  creditToken,
  confirmHTML,
  conversion,
  isSelectableDeliveryMethod,
  deliveryMethodChoices,
  isSelectableDeliveryDateTime,
  deliveryDateChoices,
  deliveryTimeChoices,
  pointAnnounce,
  isUseablePoints,
  isInputablePoints,
  pointUseageChoices,
  pointUseableValidate
} from '../apis';

const actions = {
  goToSettleEditStep: async (data) => await goToSettleEditStep(data),
  goToConfirmStep: async (data) => await goToConfirmStep(data),
  isMemberEntry: () => isMemberEntry(),
  isInputablePassword: async () => await isInputablePassword(),
  isInputablePrivacyAgree: async () => await isInputablePrivacyAgree(),
  paymentMethods: async () => await paymentMethods(),
  isSelectedCreditCard: async (data) => await isSelectedCreditCard(data),
  paymentTimeChoices: async () => await paymentTimeChoices(),
  creditToken: async (data) => await creditToken(data),
  confirmHTML: () => confirmHTML(),
  conversion: async (data) => await conversion(data),
  isSelectableDeliveryMethod: async () => await isSelectableDeliveryMethod(),
  deliveryMethodChoices: async () => await deliveryMethodChoices(),
  isSelectableDeliveryDateTime: async (data) => await isSelectableDeliveryDateTime(data),
  deliveryDateChoices: async (data) => await deliveryDateChoices(data),
  deliveryTimeChoices: async (data) => await deliveryTimeChoices(data),
  pointAnnounce: async () => await pointAnnounce(),
  isUseablePoints: async () => await isUseablePoints(),
  isInputablePoints: async (data) => await isInputablePoints(data),
  pointUseageChoices: async () => await pointUseageChoices(),
  pointUseableValidate: async (data) => await pointUseableValidate(data),
};

export default actions;