version: '3.5'
services:
  node:
    image: 'node:12-alpine'
    ports:
      - 8080:8080
      - 8888:8888
    working_dir: /app
    environment:
      - BOTUI_CHILD_ENDPOINT=https://localhost:8081
      - BOTUI_ACTIVATE_RATE=1
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    command: sh -c "yarn && npm run start"
volumes:
  node_modules:
